# Generated by Django 6.0.6 on 2026-06-10 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('hospitalization', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('normal_range', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turnaround_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lab_tests',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ORDERED', 'Commande'), ('SAMPLED', 'Preleve'), ('ASSIGNED', 'Affecte'), ('IN_PROGRESS', 'En cours'), ('RESULTED', 'Resultat saisi'), ('VALIDATED', 'Valide'), ('PUBLISHED', 'Publie'), ('CANCELLED', 'Annule')], default='ORDERED', max_length=20)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal'), ('ROUTINE', 'Routine')], default='NORMAL', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('sampled_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='laboratory/reports/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_orders', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='clinical.consultation')),
                ('hospitalization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='hospitalization.hospitalization')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='laboratory.laborder')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_order_audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_value', models.TextField(blank=True)),
                ('result_unit', models.CharField(blank=True, max_length=50)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.labtest')),
            ],
            options={
                'db_table': 'lab_order_items',
            },
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'status'], name='lab_orders_patient_d15a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', 'created_at'], name='lab_orders_status_a40478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laborderitem',
            unique_together={('order', 'test')},
        ),
    ]
