# Generated by Django 6.0.6 on 2026-06-10 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalization', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiee'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee')], default='SCHEDULED', max_length=20)),
                ('consultation_date', models.DateTimeField()),
                ('chief_complaint', models.TextField()),
                ('anamnesis', models.TextField(blank=True)),
                ('physical_exam', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('hospitalization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='hospitalization.hospitalization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient')),
            ],
            options={
                'db_table': 'consultations',
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd10_code', models.CharField(max_length=10)),
                ('icd10_label', models.CharField(max_length=500)),
                ('diag_type', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECONDARY', 'Secondaire'), ('DIFFERENTIAL', 'Differentiel')], default='PRINCIPAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.consultation')),
            ],
            options={
                'db_table': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validee'), ('DISPENSED', 'Dispensee'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical.consultation')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'consultation_date'], name='consultatio_patient_36aeed_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor', 'consultation_date'], name='consultatio_doctor__2ef287_idx'),
        ),
    ]
