# Generated by Django 6.0.6 on 2026-06-10 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=30, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='hospitalization.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_type', models.CharField(choices=[('MORNING', 'Matin'), ('AFTERNOON', 'Apres-midi'), ('NIGHT', 'Nuit'), ('ON_CALL', 'De garde')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='hospitalization.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hr.staffprofile')),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['staff', 'start_datetime'], name='shifts_staff_i_52cec3_idx'), models.Index(fields=['department', 'start_datetime'], name='shifts_departm_ba0011_idx')],
            },
        ),
    ]
